{{- $chartFullName := include "my-app-chart.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ print $chartFullName "-secret-mysql" }}
  labels:
  {{- include "my-app-chart.labels" . | nindent 4 }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (print $chartFullName "-secret-mysql")) | default dict }}
  {{- $secretData := (get $secretObj "data") }}

  {{- if $secretData }}
    {{- range $key, $value := $secretData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- else }}
  MYSQL_DATABASE: {{ .Values.secretMysql.mysqlDatabase | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secretMysql.mysqlRootPassword | default (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
type: opaque
