{{- $chartFullName := include "my-app-chart.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ print $chartFullName "-secret-node" }}
  labels:
  {{- include "my-app-chart.labels" . | nindent 4 }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (print $chartFullName "-secret-node")) | default dict }}
  {{- $secretData := (get $secretObj "data") }}

  {{- if $secretData }}
    {{- range $key, $value := $secretData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- else }}
  DATABASE_NAME: {{ .Values.secretNode.dbName | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.secretNode.dbPassword | b64enc | quote }}
  {{- end }}
type: opaque
